version: "3.7"
   
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    command: bash -c "cd api && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - variables.sh
    ports:
      - "8000:8000"
