version: "3.7"
   
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=videoapi
      - POSTGRES_USER=videoapi_user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
  web:
    build: .
    tty: true
    command: bash -c "cd api && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - variables.sh
    ports:
      - "8000:8000"
