# Generated by Django 3.2.6 on 2021-08-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.CharField(max_length=16)),
                ('published_at', models.DateTimeField()),
                ('channel_id', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail_urls', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'youtube',
            },
        ),
    ]
